export const __prod__ = process.env.NODE_ENV === 'production'
export const REDIS_PREFIX = 'bloggerum:'
export const COOKIE_NAME = 'uid'
export const TEBI_ENDPOINT = 'https://s3.tebi.io'
export const TEBI_BUCKET_NAME = 'bloggerum'
export const FORGOT_PASSWORD_PREFIX = 'forgot-password:'
export const MONGODB_POSTS_INDEX = 'post_search'
